name: Build Tangem App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  PACKAGE_NAME: "com.tangem.wallet.debug"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Decode and place google-services.json
      run: |
        echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 -d > app/google-services.json
        echo "PACKAGE_NAME=$(jq -r '.client[0].client_info.android_client_info.package_name' app/google-services.json)" >> $GITHUB_ENV

    - name: Update package name
      run: |
        sed -i "s/applicationId \".*\"/applicationId \"${{ env.PACKAGE_NAME }}\"/g" app/build.gradle

    - name: Setup Keystore
      run: |
        echo "${{ secrets.KEYSTORE_FILE }}" | base64 -d > app/keystore.jks
        echo "KEYSTORE_PATH=app/keystore.jks" >> $GITHUB_ENV

    - name: Setup GitHub Packages Auth
      run: |
        echo "gpr.user=github" >> local.properties
        echo "gpr.key=${{ secrets.PERSONAL_ACCESS_TOKEN }}" >> local.properties

    - name: Create config directory
      run: |
        mkdir -p app/src/main/assets/tangem-app-config
        touch app/src/main/assets/tangem-app-config/config_dev.json

    - name: Build APK
      run: |
        ./gradlew assembleRelease \
          -PkeystoreFile=${{ env.KEYSTORE_PATH }} \
          -PkeystorePassword=${{ secrets.KEYSTORE_PASSWORD }} \
          -PkeyAlias=${{ secrets.KEY_ALIAS }} \
          -PkeyPassword=${{ secrets.KEY_PASSWORD }}

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: tangem-release-${{ github.run_number }}
        path: app/build/outputs/apk/release/*.apk
        retention-days: 7

    - name: Cleanup sensitive files
      run: |
        rm -f ${{ env.KEYSTORE_PATH }}
        rm -f local.properties
