name: Tangem Application Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'

    - name: Install Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 34
        build-tools: 34.0.1
        ndk: '25.2.9519653'

    - name: Cache Gradle and Android SDK
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          ~/Android/Sdk/cmdline-tools
        key: cache-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/*.toml') }}
        restore-keys: |
          cache-${{ runner.os }}-

    - name: Set gradle.properties (increase heap)
      run: |
        echo "org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8" >> gradle.properties

    - name: Extract VERSION_NAME from tangem_dependencies.toml
      run: |
        LINE=$(grep 'tangemCardSdk' tangem_dependencies.toml)
        VERSION_NAME=$(echo "$LINE" | grep -oP 'releases-\K[0-9]+\.[0-9]+\.[0-9]+')
        if [ -z "$VERSION_NAME" ]; then
          echo "❌ VERSION_NAME is empty. Check tangem_dependencies.toml format"
          exit 1
        fi
        echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV
        echo "VERSION_NAME=$VERSION_NAME"

    - name: Set versionCode as current timestamp
      run: |
        VERSION_CODE=$(date +'%Y%m%d%H')
        echo "VERSION_CODE=$VERSION_CODE" >> $GITHUB_ENV

    - name: Clone external tangem-app-config
      run: |
        git clone https://github.com/Newcomer365/tangem-app-config.git
        mkdir -p app/src/main/assets/tangem-app-config/
        cp -r tangem-app-config/* app/src/main/assets/tangem-app-config/

    - name: Decode and extract package name
      run: |
        echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 --decode > app/google-services.json
        PACKAGE_NAME=$(jq -r '.client[0].client_info.android_client_info.package_name' app/google-services.json)
        echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_ENV

    - name: Update AppConfig.kt
      run: |
        sed -i 's|const val packageName = ".*"|const val packageName = "${{ env.PACKAGE_NAME }}"|' plugins/configuration/src/main/kotlin/com/tangem/plugin/configuration/model/AppConfig.kt

    - name: Download Signing Keystore and Write Properties
      run: |
        echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > ~/keystore.jks
        mkdir -p ~/.gradle
        echo "gpr.key=${{ secrets.GITHUB_TOKEN }}" > ~/.gradle/gradle.properties
        echo "gpr.user=${{ github.actor }}" >> ~/.gradle/gradle.properties

    - name: Build local.properties
      run: |
        echo "gpr.user=${{ github.actor }}" >> local.properties
        echo "gpr.key=${{ secrets.GITHUB_TOKEN }}" >> local.properties
        echo "sdk.dir=${ANDROID_HOME}" >> local.properties

    - name: Generate Debug Keystore (for fallback)
      run: |
        mkdir -p ~/.android
        keytool -genkeypair -v \
          -keystore ~/.android/debug.keystore \
          -alias androiddebugkey \
          -keyalg RSA -keysize 2048 -validity 10000 \
          -storepass android \
          -keypass android \
          -dname "CN=Android Debug, OU=Unknown, O=Unknown, L=Unknown, ST=Unknown, C=US"
        mkdir -p app/src/main/assets/tangem-app-config/android/keystore/
        echo "store_password=android" > app/src/main/assets/tangem-app-config/android/keystore/debug_keystore.properties
        echo "key_alias=androiddebugkey" >> app/src/main/assets/tangem-app-config/android/keystore/debug_keystore.properties
        echo "key_password=android" >> app/src/main/assets/tangem-app-config/android/keystore/debug_keystore.properties
        cp ~/.android/debug.keystore app/src/main/assets/tangem-app-config/android/keystore/

    - name: Build Signed APK
      run: |
        ./gradlew assembleRelease --no-daemon --max-workers=2 \
          -Pandroid.injected.signing.store.file=$HOME/keystore.jks \
          -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} \
          -Pandroid.injected.signing.key.alias=${{ secrets.KEY_ALIAS }} \
          -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }} \
          -PversionName=${{ env.VERSION_NAME }} \
          -PversionCode=${{ env.VERSION_CODE }} \
          -PpackageName=${{ env.PACKAGE_NAME }}

    - name: Rename APK
      run: |
        mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/tangem_${{ env.VERSION_NAME }}.apk

    - name: Generate SHA256
      run: |
        SHA256_HASH=$(sha256sum app/build/outputs/apk/release/tangem_${{ env.VERSION_NAME }}.apk | cut -d ' ' -f 1)
        echo "SHA256=$SHA256_HASH" >> $GITHUB_ENV

    - name: Set Tag and Release Name
      run: |
        TIMESTAMP=$(date '+%Y-%m-%d_%H-%M-%S')
        echo "TAG_NAME=v${{ env.VERSION_NAME }}_$TIMESTAMP" >> $GITHUB_ENV
        echo "RELEASE_NAME=Tangem v${{ env.VERSION_NAME }} ($TIMESTAMP)" >> $GITHUB_ENV

    - name: Create GitHub Release and Upload APK
      uses: softprops/action-gh-release@v2
      with:
        name: ${{ env.RELEASE_NAME }}
        tag_name: ${{ env.TAG_NAME }}
        body: |
          ✅ Tangem APK Release

          Version: ${{ env.VERSION_NAME }}
          SHA256: ${{ env.SHA256 }}
        files: app/build/outputs/apk/release/tangem_${{ env.VERSION_NAME }}.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Schedule Tag and Release Deletion (30 days later)
      run: |
        sudo apt-get install -y at
        echo "gh release delete ${{ env.TAG_NAME }} --yes" | at now + 30 days
        echo "gh tag delete ${{ env.TAG_NAME }}" | at now + 30 days
