name: Build Tangem App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  ANDROID_MODULE: "app"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: false  
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  

    - name: Manual submodule setup
      run: |
        git config --global url."https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com".insteadOf "https://github.com"
        git submodule sync
        git submodule update --init --recursive --remote

    - name: Validate project structure
      run: |
        test -f "${{ env.ANDROID_MODULE }}/build.gradle" || (echo "build.gradle not found"; exit 1)

    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Decode and place google-services.json
      run: |
        mkdir -p ${{ env.ANDROID_MODULE }}
        echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 -d > ${{ env.ANDROID_MODULE }}/google-services.json

    - name: Update package name
      run: |
        sed -i "s/applicationId \".*\"/applicationId \"$(jq -r '.client[0].client_info.android_client_info.package_name' ${{ env.ANDROID_MODULE }}/google-services.json)\"/g" ${{ env.ANDROID_MODULE }}/build.gradle

    - name: Setup Keystore
      run: |
        echo "${{ secrets.KEYSTORE_FILE }}" | base64 -d > ${{ env.ANDROID_MODULE }}/keystore.jks
        echo "KEYSTORE_PATH=${{ env.ANDROID_MODULE }}/keystore.jks" >> $GITHUB_ENV

    - name: Setup GitHub Packages Auth
      run: |
        echo "gpr.user=github" >> local.properties
        echo "gpr.key=${{ secrets.PERSONAL_ACCESS_TOKEN }}" >> local.properties

    - name: Create config directory
      run: |
        mkdir -p ${{ env.ANDROID_MODULE }}/src/main/assets/tangem-app-config
        echo '{}' > ${{ env.ANDROID_MODULE }}/src/main/assets/tangem-app-config/config_dev.json

    - name: Build APK
      run: |
        ./gradlew :${{ env.ANDROID_MODULE }}:assembleRelease \
          -PkeystoreFile=${{ env.KEYSTORE_PATH }} \
          -PkeystorePassword=${{ secrets.KEYSTORE_PASSWORD }} \
          -PkeyAlias=${{ secrets.KEY_ALIAS }} \
          -PkeyPassword=${{ secrets.KEY_PASSWORD }}

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: tangem-release-${{ github.run_number }}
        path: ${{ env.ANDROID_MODULE }}/build/outputs/apk/release/*.apk

    - name: Cleanup
      run: |
        rm -f ${{ env.KEYSTORE_PATH }}
