name: Build Tangem App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main repo
      uses: actions/checkout@v4

    - name: Clean existing directory
      run: |
        rm -rf app/src/main/assets/tangem-app-config
        mkdir -p app/src/main/assets

    - name: Initialize submodule
      run: |
        git submodule add --force --name tangem-app-config \
          https://github.com/Newcomer365/tangem-app-config.git \
          app/src/main/assets/tangem-app-config
        
        git submodule update --init --remote --recursive

    - name: Verify submodule
      run: |
        ls -la app/src/main/assets/tangem-app-config
        test -f app/src/main/assets/tangem-app-config/config_dev.json || exit 1

    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Decode google-services.json
      run: |
        echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 -d > app/google-services.json

    - name: Setup Keystore
      run: |
        echo "${{ secrets.KEYSTORE_FILE }}" | base64 -d > app/keystore.jks

    - name: Build APK
      run: |
        ./gradlew :app:assembleRelease \
          -PkeystoreFile=app/keystore.jks \
          -PkeystorePassword=${{ secrets.KEYSTORE_PASSWORD }} \
          -PkeyAlias=${{ secrets.KEY_ALIAS }} \
          -PkeyPassword=${{ secrets.KEY_PASSWORD }}

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: tangem-release
        path: app/build/outputs/apk/release/*.apk
