name: Create Pull request from release branch to develop

on:
  push:
    branches:
      - 'releases/**'
jobs:
  create-pr-to-develop:
    uses: tangem-developments/actions/.github/workflows/create_pr.yml@main
    with:
      source_branch: ${{ github.ref_name }}
      target_branch: develop
      replace_android_tangem_dependencies: true
    secrets:
      AUTO_MERGE_TOKEN: ${{ secrets.AUTO_MERGE_TOKEN }}