name: Create Pull request from release branch to develop

on:
  push:
    branches:
      - 'releases/**'
jobs:
  create-pr-to-develop:
    uses: tangem-developments/actions/.github/workflows/create_pr_to_develop.yml@feature/IOS-8785_ci_cd_create_release
    with:
      source_branch: ${{ github.ref_name }}
      replace_android_tangem_dependencies: true
    secrets:
      AUTO_MERGE_TOKEN: ${{ secrets.AUTO_MERGE_TOKEN }}