name: Create Pull request from release branch to develop

on:
  push:
    branches:
      - 'releases/**'
jobs:
  create-pr-to-develop:
    uses: tangem-developments/actions/.github/workflows/create_pr_to_develop.yml@feature/AND-9908_fix_create_pr_workflow
    with:
      source_branch: ${{ github.ref_name }}
      replace_android_tangem_dependencies: true
    secrets:
      AUTO_MERGE_TOKEN: ${{ secrets.AUTO_MERGE_TOKEN }}
      GH_MOBILE_PAT: ${{ secrets.GH_MOBILE_PAT }}
