# .github/workflows/prepare.yml
name: Prepare

on:
  workflow_call:
    inputs:
      initial_version_code:
        required: true
        type: number
      use_dexprotector:
        required: false
        type: boolean
        default: false
    outputs:
      version_name:
        description: "Version name"
        value: ${{ jobs.prepare.outputs.version_name }}
      version_code:
        description: "Version code"
        value: ${{ jobs.prepare.outputs.version_code }}
      jira_summary:
        description: "Jira summary"
        value: ${{ jobs.prepare.outputs.jira_summary }}

jobs:
  prepare:
    name: Prepare
    runs-on: [self-hosted, ARM64, active-android, Linux]
    outputs:
      version_name: ${{ steps.get_version_name.outputs.versionName }}
      version_code: ${{ steps.get_version_code.outputs.versionCode }}
      jira_summary: ${{ steps.jira.outputs.summary }}
    steps:
      - name: Jira Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_TOKEN }}

      - name: Get Jira Issue Number from Branch Name
        id: jira
        uses: tangem/jira-action@master
        with:
          action: getBranchSummary
          branch-name: ${{ github.ref_name }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.GH_MOBILE_PAT }}

      - name: Checkout dexprotector config
        if: ${{ inputs.use_dexprotector == true }}
        uses: actions/checkout@v3
        with:
          repository: 'tangem/private-app-config'
          ref: 'main'
          token: ${{ secrets.GH_MOBILE_PAT }}
          path: 'app-config'

      - name: Increment version code
        id: get_version_code
        env:
          RUN_NUMBER: ${{ github.run_number }}
          INITIAL_VERSION_CODE: ${{ inputs.initial_version_code }}
        run: |
          VERSION_CODE=$((RUN_NUMBER + INITIAL_VERSION_CODE))
          echo "versionCode=$VERSION_CODE" >> $GITHUB_OUTPUT

      - name: Read version.properties file
        id: get_version_name
        uses: BrycensRanch/read-properties-action@v1
        with:
          file: version.properties
          property: versionName
          default: 0.0.1

      - name: Build Docker image
        run: |
          docker build --platform linux/arm64 -t tangem_ci_android_environment .
