name: Publish internal build to Firebase App Distribution

on:
  push:
    branches:
      - 'develop'
  workflow_dispatch:
    inputs:
      build_description:
        description: >
          Optional additional info about the build
        type: string
  workflow_call:
    secrets:
      FIREBASE_APP_ID_INTERNAL:
        required: true
      FIREBASE_CLI_TOKEN:
        required: true
      # Token must have read access to all the submodule repositories
      GH_MOBILE_PAT:
        required: true

env:
  INITIAL_VERSION_CODE: ${{ 1000 }}

jobs:
  prepare:
    uses: ./.github/workflows/prepare.yml
    name: Prepare
    with:
      initial_version_code: 1000
    secrets: inherit

  build_and_publish:
    name: Build and publish
    runs-on: [ self-hosted, ARM64, active-android, Linux ]
    environment: Alpha # required for obtaining token
    needs: prepare
    steps:
      - name: Build internal
        id: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          version_code: ${{ needs.prepare.outputs.version_code }}
          version_name: ${{ needs.prepare.outputs.version_name }}
        run: |
          env > .env
          
          docker run --rm \
            --user ubuntu \
            --env-file .env \
            --volume ~/.gradle:/home/ubuntu/.gradle \
            --volume ${{ github.workspace }}:/workspace \
            tangem_ci_android_environment \
            sh -c "
              cd /workspace;
          
              fastlane buildInternal;
            "

      - name: Publish to Firebase
        id: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GH_MOBILE_PAT }}
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          app_id_internal: ${{ secrets.FIREBASE_APP_ID_INTERNAL }}
          firebase_cli_token: ${{ secrets.FIREBASE_CLI_TOKEN }}
          apk_path_internal: app/build/outputs/apk/internal/app-internal.apk
          release_notes: ${{ github.ref_name }} - ${{ github.sha }}
          groups: testers
        run: |
          env > .env
          
          docker run --rm \
            --user ubuntu \
            --env-file .env \
            --volume ${{ github.workspace }}:/workspace \
            --volume $GITHUB_OUTPUT:/workspace/github_output.txt \
            tangem_ci_android_environment \
            sh -c "
              cd /workspace;
          
              fastlane publishToFirebase;
            "

  notification:
    name: Send Notification
    needs: build_and_publish
    uses: tangem-developments/actions/.github/workflows/notification.yml@main
    with:
      channel: 'deployments-android'
      status: 'success'
      app_name: 'Tangem Internal'
      deploy_to: 'Firebase app distribution'
      version: ${{ needs.build_and_publish.outputs.version_name }}
      build_number: ${{ needs.build_and_publish.outputs.version_code }}
      changelog: ${{ needs.build_and_publish.outputs.jira_summary }}
      build_description: ${{ inputs.build_description }}
      encoded_release_url: ${{ needs.build_and_publish.outputs.encoded_release_url }}
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  error_notification:
    name: Error Notification
    needs: build_and_publish
    if: failure()
    uses: tangem-developments/actions/.github/workflows/notification.yml@main
    with:
      channel: 'deployments-android'
      status: 'error'
      app_name: 'Tangem Internal'
      deploy_to: 'Firebase App Distribution'
      version: ${{ needs.build_and_publish.outputs.version_name }}
      build_number: ${{ needs.build_and_publish.outputs.version_code }}
      changelog: ${{ needs.build_and_publish.outputs.jira_summary }}
      build_description: ${{ inputs.build_description }}
      encoded_release_url: ${{ needs.build_and_publish.outputs.encoded_release_url }}
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
