name: Jira - Set 'Next Release' version for the merged Jira task

on:
  pull_request:
    branches:
      - 'develop'
      - 'releases/*'
    types:
      - closed

jobs:
  prepare:
    name: Prepare Release
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    outputs:
      version_name: ${{ steps.version.outputs.VERSION_NAME }}
    steps:
      - name: Determine Version Name
        id: version
        run: |
          if [[ "${{ github.base_ref }}" == "develop" ]]; then
            echo "VERSION_NAME=Next Release" >> $GITHUB_OUTPUT
          elif [[ "${{ github.base_ref }}" == releases/* ]]; then
            VERSION=$(echo "${{ github.base_ref }}" | sed 's/releases\///')
            echo "VERSION_NAME=${VERSION}.0" >> $GITHUB_OUTPUT
          fi

  set-jira-version:
    name: Set Jira Task Version
    needs: prepare
    uses: tangem-developments/actions/.github/workflows/set-jira-task-version.yml@feature/AND-9908_fix_set_jira_version_workflow
    with:
      version_name: ${{ needs.prepare.outputs.version_name }}
      project_name: 'AND'
    secrets:
      JIRA_BASE_URL: ${{ secrets.JIRA_URL }}
      JIRA_USER_EMAIL: ${{ secrets.JIRA_USER }}
      JIRA_API_TOKEN: ${{ secrets.JIRA_TOKEN }}
      GH_MOBILE_PAT: ${{ secrets.GH_MOBILE_PAT }}
