name: Jira - Set 'Next Release' version for the merged Jira task

on:
  pull_request:
    branches:
      - 'develop'
    types:
      - closed

jobs:
  prepare:
    name: Prepare Release
    if: ${{ github.event.pull_request.merged }}
    uses: tangem-developments/actions/.github/workflows/set-jira-task-version.yml@feature/AND-9908_create_release
    with:
      next_version_name: 'Next Release'
      project_name: 'AND'
    secrets:
      JIRA_BASE_URL: ${{ secrets.JIRA_URL }}
      JIRA_USER_EMAIL: ${{ secrets.JIRA_USER }}
      JIRA_API_TOKEN: ${{ secrets.JIRA_TOKEN }}
