name: Sync Fork

#on:
  #push:
    #branches:
      #- master
  #pull_request:
    #branches:
      #- master
  #schedule:
    #- cron: '0 1 * * *'

jobs:
  sync:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Sync Fork
      uses: tgymnich/fork-sync@v2.0
      with:
        owner: tangem
        base: master
        head: master

    - name: Trigger Compile Workflow
      uses: peter-evans/repository-dispatch@v3
      with:
        workflow: 'build.yml'  
        ref: master
