name: Sync Tangem New Repo

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  sync-new-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout old repo
        uses: actions/checkout@v3
        with:
          ref: master
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean old repo
        run: |
          if [ -d ".github" ]; then
            find . -mindepth 1 -maxdepth 1 ! -name ".github" -exec rm -rf {} +
          else
            rm -rf *
          fi

      - name: Clone new repo
        run: |
          git clone --depth=1 https://github.com/tangem/tangem-app-android.git newrepo
          if [ ! -d "newrepo" ]; then
            exit 1
          fi

      - name: Sync new repo files in batches
        run: |
          for dir in $(ls -A newrepo); do
            if [ "$dir" != ".github" ]; then
              rsync -a newrepo/$dir/ ./$dir/ 2>/dev/null || cp -r newrepo/$dir ./
              git add $dir || true
              git commit -m "Sync $dir from new repo" || true
            fi
          done
          rm -rf newrepo

      - name: Force push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git push -f https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git master

      - name: Trigger build workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build.yml
          ref: master
          token: ${{ secrets.GITHUB_TOKEN }}
